// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseAutoSync():Promise<string>;

export function DbConnTest():Promise<string>;

export function ReadConf():Promise<string>;

export function Save():Promise<string>;

export function SaveConf(arg1:string):Promise<string>;

export function StartAutoSync():Promise<string>;

export function Sync():Promise<string>;

export function XzxConnTest():Promise<string>;
